# @package _global_
model:
  charset_train: " \u09a9\u09e57নঊ৮ঔেওৃ৸শফঃৱঅাঘজৰ2০ঋৌ\u09b55মখ৵ঽ\u09b3ইঢঙ9ৠ৫৴ঠ৻\u09c5ৣ3ঁধত1৷ষদুঐপএণৄকভ\u09e4চহিৗ৩৬৪\u09b1৺\u09b4ংঞঌযী84৹্রঈডঢ়6২থসৈৢ0৲৯৭৳\u09dbছ\u09deলূঝয়৶গৡৼটৎ়আড়উব১ো"
  charset_test: " \u09a9\u09e57নঊ৮ঔেওৃ৸শফঃৱঅাঘজৰ2০ঋৌ\u09b55মখ৵ঽ\u09b3ইঢঙ9ৠ৫৴ঠ৻\u09c5ৣ3ঁধত1৷ষদুঐপএণৄকভ\u09e4চহিৗ৩৬৪\u09b1৺\u09b4ংঞঌযী84৹্রঈডঢ়6২থসৈৢ0৲৯৭৳\u09dbছ\u09deলূঝয়৶গৡৼটৎ়আড়উব১ো"
